# Generated by Django 6.0.2 on 2026-03-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_expire_minutes', models.PositiveIntegerField(default=10, help_text='How long the OTP is valid for (in minutes).')),
                ('otp_max_attempts', models.PositiveIntegerField(default=5, help_text='Maximum failed attempts before OTP is invalidated.')),
                ('max_cv_size_mb', models.PositiveIntegerField(default=5, help_text='Maximum allowed size for CV uploads (in MB).')),
                ('max_logo_size_mb', models.PositiveIntegerField(default=2, help_text='Maximum allowed size for company logo uploads (in MB).')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable to put the platform in maintenance mode.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
