# Generated by Django 6.0.2 on 2026-03-15 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_rejection_reason_job_reviewed_at_job_reviewed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Automatically set to True if the job receives 5+ reports. Hides the job from public listings.'),
        ),
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam / Scam'), ('misleading', 'Misleading / Fake'), ('inappropriate', 'Inappropriate Content'), ('duplicate', 'Duplicate Posting'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Additional context from the user')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed & Action Taken'), ('dismissed', 'Dismissed (False Alarm)')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.job')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', 'status'], name='jobs_jobrep_job_id_87c5f2_idx'), models.Index(fields=['status', '-created_at'], name='jobs_jobrep_status_fa1615_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reporter__isnull', False)), fields=('job', 'reporter'), name='unique_job_report')],
            },
        ),
    ]
