# Generated by Django 5.1.4 on 2026-03-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('verify_email', 'Verify Email'), ('reset_password', 'Reset Password')], default='verify_email', max_length=20),
        ),
    ]
