# Generated by Django 5.1.4 on 2026-03-08 02:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g. "Technical Round 1", "HR Screening"', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Agenda, preparation instructions, dress code, etc.')),
                ('interview_type', models.CharField(choices=[('in_person', 'In Person'), ('video', 'Video Call'), ('phone', 'Phone Call')], default='video', max_length=20)),
                ('scheduled_at', models.DateTimeField(help_text='Date and time the interview starts')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration in minutes (15–480)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)])),
                ('location', models.CharField(blank=True, help_text='Physical address for in-person interviews', max_length=500)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom / Teams / Google Meet link for video interviews')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation (filled when status=cancelled)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.application')),
                ('scheduled_by', models.ForeignKey(help_text='Employer who created this interview', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='Overall rating (1–5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('technical_rating', models.PositiveSmallIntegerField(blank=True, help_text='Technical skills rating (1–5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.PositiveSmallIntegerField(blank=True, help_text='Communication rating (1–5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cultural_fit_rating', models.PositiveSmallIntegerField(blank=True, help_text='Cultural fit rating (1–5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('strengths', models.TextField(blank=True, help_text='Candidate strengths')),
                ('weaknesses', models.TextField(blank=True, help_text='Areas for improvement')),
                ('notes', models.TextField(blank=True, help_text='General notes')),
                ('recommendation', models.CharField(choices=[('strong_yes', 'Strong Yes'), ('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No'), ('strong_no', 'Strong No')], help_text='Overall hiring recommendation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='interviews.interview')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Feedback',
                'verbose_name_plural': 'Interview Feedbacks',
            },
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['application', 'status'], name='interviews__applica_96ea9d_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['scheduled_by', 'status'], name='interviews__schedul_dccb2f_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['scheduled_at'], name='interviews__schedul_0e9070_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status', 'scheduled_at'], name='interviews__status_39545c_idx'),
        ),
    ]
