# Generated by Django 6.0.2 on 2026-03-15 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_684eac_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_028906_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='recipient',
            new_name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('application_received', 'Application Received'), ('application_status_changed', 'Application Status Changed'), ('interview_scheduled', 'Interview Scheduled'), ('interview_confirmed', 'Interview Confirmed'), ('interview_cancelled', 'Interview Cancelled'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected'), ('announcement', 'Announcement')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_object_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
